Repository Houlak/hklogger, pull requests merged in 2023-05, with the labels that each got.

#4 [Bugfix] - Fix save logs in host when running the app on physical device
  .gitignore
  README.md
  Scripts/ClientScript.swift
  Sources/HKLogger/HKLogger.swift
  Sources/HKLogger/HostConnection/Connection.swift
  Sources/HKLogger/HostConnection/LogData.swift
  Sources/HKLogger/HostConnection/Notification.swift
  Sources/HKLogger/HostConnection/Server.swift
Labels: bugfix

#5 [Refactor] Remove throws
  Sources/HKLogger/Documentation.docc/GettingStarted.md
  Sources/HKLogger/Errors/HKLoggerError.swift
  Sources/HKLogger/HKLogger.swift
  docs/data/documentation/hklogger.json
  docs/data/documentation/hklogger/gettingstarted.json
  docs/data/documentation/hklogger/hklogger.json
  docs/data/documentation/hklogger/hklogger/configure().json
  docs/data/documentation/hklogger/hklogger/environment.json
  docs/data/documentation/hklogger/hklogger/hostlogsdirectory.json
  docs/data/documentation/hklogger/hklogger/includemetadataonconsole.json
  docs/data/documentation/hklogger/hklogger/includemetadataonfile.json
  docs/data/documentation/hklogger/hklogger/log(message:severity:type:filename:functionname:linenumber:).json
  docs/data/documentation/hklogger/hklogger/logsdirectoryname.json
  docs/data/documentation/hklogger/hklogger/savelogstofile.json
  docs/data/documentation/hklogger/hklogger/shared.json
  docs/data/documentation/hklogger/hkloggerenv.json
  docs/data/documentation/hklogger/hkloggerenv/!=(_:_:).json
  docs/data/documentation/hklogger/hkloggerenv/debug.json
  docs/data/documentation/hklogger/hkloggerenv/equatable-implementations.json
  docs/data/documentation/hklogger/hkloggerenv/release.json
  docs/data/documentation/hklogger/hkloggererror.json
  docs/data/documentation/hklogger/hkloggererror/couldnotsavetofile(logmessage:).json
  docs/data/documentation/hklogger/hkloggererror/debugmessage.json
  docs/data/documentation/hklogger/hkloggererror/error-implementations.json
  docs/data/documentation/hklogger/hkloggererror/localizeddescription.json
  docs/data/documentation/hklogger/hkloggererror/message.json
  docs/data/documentation/hklogger/hkloggerseveritylevel.json
  docs/data/documentation/hklogger/hkloggerseveritylevel/!=(_:_:).json
  docs/data/documentation/hklogger/hkloggerseveritylevel/equatable-implementations.json
  docs/data/documentation/hklogger/hkloggerseveritylevel/error.json
  docs/data/documentation/hklogger/hkloggerseveritylevel/icon.json
  docs/data/documentation/hklogger/hkloggerseveritylevel/info.json
  docs/data/documentation/hklogger/hkloggerseveritylevel/prefix.json
  docs/data/documentation/hklogger/hkloggerseveritylevel/warning.json
  docs/data/documentation/hklogger/hkloggertype.json
  docs/data/documentation/hklogger/hkloggertype/analytics.json
  docs/data/documentation/hklogger/hkloggertype/default.json
  docs/data/documentation/hklogger/hkloggertype/message.json
  docs/data/documentation/hklogger/hkloggertype/networking(request:response:responsebody:).json
  docs/data/documentation/hklogger/hkloggertype/prefix.json
  docs/data/documentation/hklogger/hkloggertype/trace.json
  docs/index/index.json
Labels: refactor

#6 [Feature] - Network interceptor
  Sources/HKLogger/Documentation.docc/GettingStarted.md
  Sources/HKLogger/HKLogger.swift
  Sources/HKLogger/NetworkInterceptor/HKLoggerUrlProtocol.swift
Labels: feature
